Howso:
  client: howso.direct.HowsoDirectClient
  client_extra_params:
     debug: true
     check_version: false 
     amalgam:
        library_postfix: -mt-noavx
        trace: true 
        execution_trace_dir: ./traces/